<div class="jumbotron">
  <div class="container">
      <h2> <?php echo $this->translate('Consiga algo que precisa, doe ou peça emprestado'); ?> </h2>
      <p>  <?php echo $this->translate('O'); ?> <b><?php echo $this->translate('Vizinhocas'); ?></b> 
           <?php echo $this->translate('é um portal de trocas de bens, serviços e conhecimento entre vizinhos,
                                        com o objetivo de promover o uso racional dos recursos do planeta bem como
                                        realçar a convivialidade perdida em nossas vizinhanças'); ?>
      </p>
      <a class="btn btn-success btn-lg" role="button">Cadastre-se &raquo;</a>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
          <h3 class="txt-green">Como Funciona</h3>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p><a class="btn btn-default" href="#" role="button">Saiba Mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
          <h3 class="txt-green">Cadastre-se</h3>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p class="txt-gray">.</p>
          <p><a class="btn btn-default" href="#" role="button">Saiba Mais &raquo;</a></p>
    </div>
    <div class="col-md-4">
          <h3 class="txt-green">Iniciativa</h3>
          <p class="txt-gray">O Vizinhocas é um projeto idealizado e realizado pela Coolmeia</p>
          <img src="/img/coolmeia-logo.png" />
          <p></p>
    </div>
  </div>
</div>

<hr>



<div class="actions clearfix">
  <div class="btns">
    <a class="btn submit" href="/admin/index/save" title="Criar Post">Criar Post</a>
  </div>
</div>  

<label class="divisor"><span>Lista de Manifestações</span></label>
<table class="datatable">
  <thead>
    <tr>
      <th>Título</th>
      <th>Texto</th>
      <th width="130" class="center">Data de Cadastro</th>
      <th width="120" class="center">Opções</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($posts as $post):?>
      <tr>
        <td><?php echo $this->escapeHtml($post['title']);?></td>
        <td><?php echo $this->escapeHtml($post['description']);?></td>
        <td class="center">
          <?php 
            echo $this->dateFormat($post['post_date'], \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT, 'pt_BR');
          ?>
        </td>
        <td class="center">
          <a href="/admin/index/save/id/<?php echo $post['id'] ;?>" title="Editar" class="btn"><i class="icon-edit"></i></a>
          <a href="/admin/index/delete/id/<?php echo $post['id'];?>" rel="confirmation" title="Deseja excluir este registro?" class="btn"><i class="icon-remove"></i></a>
        </td>
      </tr>
    <?php endforeach;?>
</table>
<?php

echo $this->paginationControl(
      $manifest,
      'Sliding',
      'partials/paginator/control.phtml'
);

?>
